export const TRACKS = [
  { id: '1', name: 'Aditya Rikhari (Paaro)', src: '/music/Aditya Rikhari - Paaro.mp3' },
  { id: '2', name: 'Aditya Rikhari (Sahiba)', src: '/music/Aditya Rikhari - Sahiba.mp3' },
  { id: '3', name: 'Aerosmith (Dream On)', src: '/music/Aerosmith - Dream On.mp3' },
  { id: '4', name: 'Anirudh Ravichander (Why This Kolaveri Di)', src: '/music/Anirudh_Ravichander,_Dhanush_Why_This_Kolaveri_Di_The_Soup_of_Love.mp3' },
  { id: '5', name: 'Arijit Singh (Enna Sona)', src: '/music/Arijit Singh - Enna Sona From OK Jaanu.mp3' },
  { id: '6', name: 'Arijit Singh (Main Dhoondne)', src: '/music/Arijit Singh - Main Dhoondne Ko Zamaane Mein.mp3' },
  { id: '7', name: 'Arijit Singh (Pal Pal Dil Ke Paas)', src: '/music/Arijit Singh - Pal Pal Dil Ke Paas Title Track.mp3' },
  { id: '8', name: 'Arijit Singh (Yeh Fitoor Mera)', src: '/music/Arijit Singh - Yeh Fitoor Mera.mp3' },
  { id: '9', name: 'Atif Aslam (Piya O Re Piya)', src: '/music/Atif Aslam  Shreya Ghoshal - Piya O Re Piya.mp3' },
  { id: '10', name: 'Atif Aslam (Tere Liye)', src: '/music/Atif Aslam  Shreya Ghoshal - Tere Liye.mp3' },
  { id: '11', name: 'Atif Aslam (Tere Liye Dance Mix)', src: '/music/Atif Aslam, Shreya Ghoshal - Tere Liye Dance Mix.mp3' },
  { id: '12', name: 'Djo (End of Beginning)', src: '/music/Djo, Joe Keery - End of Beginning.mp3' },
  { id: '13', name: 'Bohemia (Ek Tera Pyar)', src: '/music/Ek_Tera_Pyar.mp3' },
  { id: '14', name: 'Falak Shabbir (Mera)', src: '/music/Falak Shabbir, Falak Shabbir, Falak Shabbir - Mera.m4a' },
  { id: '15', name: 'Gajendra Verma (Mann Mera)', src: '/music/Gajendra Verma - Mann Mera Original Version.m4a' },
  { id: '16', name: 'Harshit Saxena (Hale Dil)', src: '/music/Harshit Saxena - Hale Dil.mp3' },
  { id: '17', name: 'A.R. Rahman (Guzarish)', src: '/music/JAVED ALI, AR RAHMAN, PRASOON JOSHI - GUZARISH.mp3' },
  { id: '18', name: 'Jeet Gannguli (Jo Tere Sang)', src: '/music/Jeet Gannguli - Jo Tere Sang.mp3' },
  { id: '19', name: 'Mustafa Zahid (Jo Tere Sang Alt)', src: '/music/Jeet Gannguli, Mustafa Zahid, Sayeed Quadri - Jo T.m4a' },
  { id: '20', name: 'Jind Universe (High On You)', src: '/music/Jind Universe - High On You.mp3' },
  { id: '21', name: 'KK (Piya Aaye Na)', src: '/music/KK  Tulsi Kumar - Piya Aaye Na.mp3' },
  { id: '22', name: 'KK (Ajab Si)', src: '/music/KK, VishalShekhar, Vishal Dadlani - Ajab Si.mp3' },
  { id: '23', name: 'Kailash Kher (Teri Deewani)', src: '/music/Kailash Kher, Paresh Kamath, Naresh Kamath - Teri .mp3' },
  { id: '24', name: 'Karun (Maharani)', src: '/music/Karun  Lambo Drive - Maharani.mp3' },
  { id: '25', name: 'Keane (Somewhere Only We Know)', src: '/music/Keane - Somewhere Only We Know.mp3' },
  { id: '26', name: 'Maanu (Jhol)', src: '/music/Maanu, Annural Khalid - Jhol.mp3' },
  { id: '27', name: 'Maanu (Jhol Acoustic)', src: '/music/Maanu, Annural Khalid, Abdullah Siddiqui - Jhol  A.m4a' },
  { id: '28', name: 'Michael Bublé (Feeling Good)', src: '/music/Michael Bubl - Feeling Good.m4a' },
  { id: '29', name: 'Mohit Chauhan (Mon Hariye Beghorey)', src: '/music/Mohit Chauhan, Jeet Gannguli - Mon Hariye Beghorey.m4a' },
  { id: '30', name: 'Palak Muchhal (Chahun Main Ya Naa)', src: '/music/Palak_Muchhal,_Arijit_Singh,_Jeet_Gangulli,_Irshad_Kamil_Chahun.mp3' },
  { id: '31', name: 'James (Bheegi Bheegi)', src: '/music/Pritam  James - Bheegi Bheegi From Gangster.mp3' },
  { id: '32', name: 'Salman Khan (Hangover)', src: '/music/SALMAN_KHAN,_SHREYA_GHOSHAL,_MEET_BROS_ANJJAN,_KUMAAR_HANGOVER.mp3' },
  { id: '33', name: 'Atif Aslam (Toota Jo Kabhi Tara)', src: '/music/SachinJigar, Atif Aslam, Sumedha Karmahe - Toota J.m4a' },
  { id: '34', name: 'Samidh Mukherjee (Koka Kola)', src: '/music/Samidh Mukherjee, Kalpona Patoary - Koka Kola Orig.mp3' },
  { id: '35', name: 'Sanam (Gulabi Aankhen)', src: '/music/Sanam - Gulabi Aankhen.mp3' },
  { id: '36', name: 'Talwiinder (Khayaal)', src: '/music/Talwiinder  NDS - Khayaal.mp3' },
  { id: '37', name: 'Talwiinder (Unforgettable)', src: '/music/Talwiinder - Unforgettable.mp3' },
  { id: '38', name: 'Talwiinder (Haseen)', src: '/music/Talwiinder, NDS, Rippy Grewal - Haseen.m4a' },
  { id: '39', name: 'Timir (Dui Prithibi)', src: '/music/Timir, Rana Mazumder, Jeet Gannguli - Dui Prithibi.mp3' },
  { id: '40', name: 'Yashraj (Dhundhala)', src: '/music/Yashraj, Dropped Out,  Talwiinder - Dhundhala.mp3' },
  { id: '41', name: 'Sufr (Bargad)', src: '/music/sufr, Arpit Bala, toorjo dey - bargad.m4a' },
]
